/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.modules.common {
    export class RuleUI extends View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("modules/common/Rule");
        }
    }
    REG("ui.modules.common.RuleUI",RuleUI);
}
export module ui.modules.mahjong {
    export class MahjongUI extends Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("modules/mahjong/Mahjong");
        }
    }
    REG("ui.modules.mahjong.MahjongUI",MahjongUI);
    export class MahjongHomeUI extends View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("modules/mahjong/MahjongHome");
        }
    }
    REG("ui.modules.mahjong.MahjongHomeUI",MahjongHomeUI);
    export class MahjongResultUI extends View {
		public btnNext:Laya.Image;
		public btnHome:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("modules/mahjong/MahjongResult");
        }
    }
    REG("ui.modules.mahjong.MahjongResultUI",MahjongResultUI);
}