/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.modules.mahjong {
    export class MahjongUI extends Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("modules/mahjong/Mahjong");
        }
    }
    REG("ui.modules.mahjong.MahjongUI",MahjongUI);
    export class MahjongResultUI extends View {
		public btnHome:Laya.Button;
		public btnNext:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("modules/mahjong/MahjongResult");
        }
    }
    REG("ui.modules.mahjong.MahjongResultUI",MahjongResultUI);
    export class MainInfoUI extends Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("modules/mahjong/MainInfo");
        }
    }
    REG("ui.modules.mahjong.MainInfoUI",MainInfoUI);
}