/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import MahjongMdr from "./modules/mahjong/view/MahjongMdr"
import BarProgress from "./script/BarProgress"
import MahjongHomeMdr from "./modules/mahjong/view/MahjongHomeMdr"
import MahjongResultMdr from "./modules/mahjong/view/MahjongResultMdr"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="showall";
    static screenMode:string="none";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="modules/mahjong/MahjongHome.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("modules/mahjong/view/MahjongMdr.ts",MahjongMdr);
        reg("script/BarProgress.ts",BarProgress);
        reg("modules/mahjong/view/MahjongHomeMdr.ts",MahjongHomeMdr);
        reg("modules/mahjong/view/MahjongResultMdr.ts",MahjongResultMdr);
    }
}
GameConfig.init();